In [14]:
import numpy as np
#key properties of numpy:
sales = [ 0, 155, 5, 0, 1546, 847, 234]
sales_array = np.array(sales)
print(type(sales_array))
print(f"ndim: {sales_array.ndim}") #no of dimension
print(sales_array.shape) #size of the array for each dimension
print(sales_array.size) #total no of elements
print(sales_array.dtype) #data type of the elements

<class 'numpy.ndarray'>
ndim: 1
(7,)
7
int32


In [12]:
# 2 dimentional array; add 1 to all the numbers
array = np.array([range(5), range(5)])
print(array +1)
print(array.shape)
print(array.size)
print(array.T.shape)#transpose or swap the axes
print(array.T)
print(array.ndim)
print(array.dtype)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
10
(5, 2)
[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]]
2
int32


In [13]:
np.array(['I', 'love','Python']) #max length =6

array(['I', 'love', 'Python'], dtype='<U6')

In [15]:
#reshape - changes the shape without altering its data
my_list = [x* 10 for x in range(1,11)]
my_array = np.array(my_list).reshape(10,1) #10 rows and 1 columns
my_array

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [24]:
#array creation
np.ones(4,)  #np.ones((rows, cols), dtype)
np.ones(2, dtype='int')

array([1, 1])

In [17]:
np.zeros((2,5), dtype=int)   #np.zeros((rows, cols), dtype)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
np.arange(10)        #np.arange(start, stop, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0,100,5)   #np.linspace(start, stop, n)

array([  0.,  25.,  50.,  75., 100.])

In [20]:
np.arange(1,9,2).reshape(2,2)    #np.array.reshape(rows, cols)

array([[1, 3],
       [5, 7]])

In [25]:
np.identity(10)     #identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
from numpy.random import default_rng
rng = default_rng(12345)
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [27]:
rng = default_rng(12345)
mean, stddev = 5,1
random_normal = rng.normal(mean, stddev, size=10)
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [28]:
rng = np.random.default_rng(616)
rng.random(5)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588])

In [29]:
rng.integers(0, 10, 100)

array([6, 0, 1, 8, 0, 7, 3, 7, 9, 5, 8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1,
       2, 5, 1, 8, 9, 0, 3, 1, 5, 8, 0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9,
       4, 1, 6, 1, 4, 4, 9, 5, 3, 4, 7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5,
       8, 2, 3, 0, 0, 8, 3, 8, 4, 8, 8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3,
       2, 0, 0, 4, 9, 5, 4, 1, 8, 2, 7, 7], dtype=int64)

In [30]:
rng.normal(50,5,10)

array([58.79869416, 47.36546164, 50.41694017, 47.18838872, 50.68654664,
       53.53115044, 46.35468178, 46.1580894 , 52.89177118, 45.90693639])

In [31]:
#create a 3*3 array of random numbers between 0 and 1. Use a random state of 2022.
rng = np.random.default_rng(2022)
random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [33]:
#Indexing and Slicing
integer_array = np.arange(12)
new_array = integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
new_array[:,:]    #everything

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
new_array[0, 0:4]

array([0, 1, 2, 3])

In [37]:
new_array[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
new_array[:,3]

array([ 3,  7, 11])

In [40]:
new_array[2,2]

10

In [41]:
#Array operations
import numpy as np
rng = np.random.default_rng(616)
inventory = rng.integers(0,100,10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [42]:
inventory - 24    #concept of broadcasting, operate element wise

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [44]:
(inventory / 2).dtype

dtype('float64')

In [46]:
price = (rng.random(10)*10).round(2)
price

array([5.24, 8.02, 0.75, 1.51, 8.97, 6.63, 7.26, 7.66, 0.3 , 7.78])

In [49]:
(price * inventory).sum()  #sum of all inventory

2477.33

In [50]:
inventory_list = list(inventory)   #convert numpy arrays into python sequence data type

In [51]:
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [52]:
inventory_list +2

TypeError: can only concatenate list (not "int") to list

In [53]:
new_inventory = []
for x in inventory_list:
    new_inventory.append(x+2)

new_inventory

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [54]:
[x + 2 for x in inventory_list]

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [3]:
#FILTERING ARRAY 
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [5]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
even_odd = np.array(['even','odd'] * 10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [7]:
#MODIFICATION OF ARRAY VALUES
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [8]:
even_odd[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [9]:
my_array[even_odd != 'odd'] = 0
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [10]:
my_array[2] = 2
my_array

array([ 0,  1,  2,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [11]:
mask = (even_odd != 'odd') | (even_odd != 'even')
even_odd[mask]

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [12]:
#The WHERE Function
import numpy as np
np.where(my_array % 2 ==0 , 'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [13]:
np.where(my_array % 2 ==0 , 'even', np.where(my_array == 9, my_array, 'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U11')

In [20]:
#ARRAY AGGREGATION METHODS
import numpy as np
rng = np.random.default_rng(616)
price = (rng.random(10) * 10).round(2)
price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [21]:
inventory = rng.integers(0,100,10)
inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43], dtype=int64)

In [22]:

inventory.mean()

35.3

In [23]:
inventory.sum()

353

In [24]:
inventory.min()

6

In [25]:
inventory.max()

80

In [26]:
inventory.std()

20.48438429633656

In [28]:
(price * inventory).sum()

1848.2900000000002

In [29]:
(price * inventory).mean()

184.829

In [30]:
(price * inventory).argmax()   #index of the max element

0

In [31]:
(price * inventory).argmin()   

3

In [33]:
price_2d = price.reshape(5,2)
price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [34]:
price_2d.sum(axis=0)

array([30.45, 25.55])

In [35]:
price_2d.sum(axis=1)

array([12.63,  7.66,  6.63, 16.14, 12.94])

In [40]:
#ARRAY FUNCTIONS
import  numpy as np
price = np.array([2.6, 7.2, 6.92, 3.88, 0.78, 2.67, 8.87, 0.23, 5.23, 6.3])
inventory =  np.array([79, 22, 20, 48, 8,76, 12, 16, 5, 64])
product_value = price * inventory
product_value.sort()
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [41]:
reshaped_product_value = product_value.reshape(2,5)
reshaped_product_value

array([[  3.68,   6.24,  26.15, 106.44, 138.4 ],
       [158.4 , 186.24, 202.92, 205.4 , 403.2 ]])

In [42]:
np.median(reshaped_product_value)

148.4

In [43]:
np.percentile(reshaped_product_value, 50)

148.4

In [44]:
np.sqrt(reshaped_product_value)

array([[ 1.91833261,  2.4979992 ,  5.11370707, 10.3169763 , 11.76435294],
       [12.58570618, 13.64697769, 14.24499912, 14.33178286, 20.07984064]])

In [45]:
np.unique(reshaped_product_value)

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [46]:
np.unique(np.ones(100))

array([1.])

In [47]:
import numpy as np
product_value = np.array([205.4, 158.4, 138.4, 186.24, 6.24, 202.92, 106.44, 3.68, 26.15, 403.2])
product_value

array([205.4 , 158.4 , 138.4 , 186.24,   6.24, 202.92, 106.44,   3.68,
        26.15, 403.2 ])

In [50]:
np.sort(product_value)[:5]   #get bottom five prices , Returns a new sorted array and Does NOT change the original array

array([  3.68,   6.24,  26.15, 106.44, 138.4 ])

In [51]:
product_value.sort()     #Sorts the array in-place and Changes the original array

In [52]:
product_value

array([  3.68,   6.24,  26.15, 106.44, 138.4 , 158.4 , 186.24, 202.92,
       205.4 , 403.2 ])

In [53]:
product_value[::-1]     #descending or reserve order

array([403.2 , 205.4 , 202.92, 186.24, 158.4 , 138.4 , 106.44,  26.15,
         6.24,   3.68])